name = "v4f-test-create-pack"
author = "v4f"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31d62c084b40915644bd2c0938996faaa12d8eae35943e5c3a81aef7a96455c0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
