name = "v4f-test-create-pack"
author = "v4f"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9105feb548967a0536587bbe766d4c4f8da76fd57d073478778a8011dcf8c339"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
