name = "v4f-test-create-pack"
author = "v4f"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a74efc361475326f06d928f8deccac53192a84f8731ba3499266ced1fb31d326"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
